kind: pipeline
type: kubernetes
name: Build recruitunit

steps:
#  - name: pre-check
#    image: docker
#    environment:
#      USERNAME:
#        from_secret: username
#      PASSWORD:
#        from_secret: password
#      foo: bar
#    commands:
#      - echo $USERNAME
#      - echo $PASSWORD
#      - echo $foo

  - name: build recruitunit
    image: docker:19-dind
    volumes:
      - name: dockersock
        path: /var/run
      - name: buildtarget
        path: /dist
    commands:
      - sleep 10 # give docker enough time to start
      - docker --version
      - docker build -t recruitunit:latest .
      - docker run --rm --name recruitunit-build -v $(pwd)/dist:/app/dist recruitunit:latest

  - name: deploy recruitunit to harbor
    image: plugins/docker:19
    settings:
      registry: 'harbor-bitnami.default'
      repo: 'harbor-bitnami.default/homelab/recruitunit-frontend'
      username:
        from_secret: username
      password:
        from_secret: password
      dockerfile: ./Dockerfile-nginx
      debug: true
      launch_debug: true
      insecure: true
      use_cache: false

#  - name: configure bardly namespace
#    image: sinlead/drone-kubectl
#    failure: ignore
#    settings:
#      kubernetes_server:
#        from_secret: drone_k8s_server
#      kubernetes_cert:
#        from_secret: drone_k8s_cert
#      kubernetes_token:
#        from_secret: drone_k8s_token
#    commands:
#      - kubectl create namespace bardly
#      - kubectl get secret harbor-registry-credentials --namespace=default -oyaml | grep -v '^\s*namespace:\s' | kubectl apply --namespace=bardly -f -

  - name: deploy recruitunit to kubernetes
    image: sinlead/drone-kubectl
    settings:
      # These secrets are defined via the Drone UI repo settings page
      kubernetes_server:
        from_secret: drone_k8s_server
      kubernetes_cert:
        from_secret: drone_k8s_cert
      kubernetes_token:
        from_secret: drone_k8s_token
    commands:
      - kubectl delete -f recruitunit-manifest.yaml --namespace=bardly
      - kubectl apply -f recruitunit-manifest.yaml --namespace=bardly

services:
  - name: docker
    image: docker:19-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
  - name: buildtarget
    temp: {}

---
kind: secret
name: username
get:
  path: secret-stewart-harbor
  name: username

---
kind: secret
name: password
get:
  path: secret-stewart-harbor
  name: password