kind: pipeline
type: kubernetes
name: Build recruitunit

steps:
  - name: build recruitunit
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
      - name: buildtarget
        path: /dist
    commands:
      - sleep 10 # give docker enough time to start
      - docker ps -a
      - docker build -t recruitunit:latest .
      - docker run --rm --name recruitunit-build -v $(pwd)/dist:/app/dist recruitunit:latest
      - docker build -t recruitunit-frontend:latest -f Dockerfile-nginx .
      - docker ps -a
      - docker images
      - ls -la
      - echo "list items in pwd[$(pwd)]:"
      - ls -la $(pwd)/dist

  - name: deploy recruitunit to harbor
    image: plugins/docker
    settings:
      registry: 'harbor-bitnami.default'
      repo: 'harbor-bitnami.default/homelab/recruitunit-frontend'
      username: stewart
      password: stJ0hnstuHARBOR #todo: replace with secret
      dockerfile: ./Dockerfile-nginx
      debug: true
      launch_debug: true
      insecure: true
      use_cache: false

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
  - name: buildtarget
    temp: {}