kind: pipeline
type: kubernetes
name: Build recruitunit

steps:
  - name: build recruitunit
    image: docker:dind
    settings:
      registry: 'harbor-bitnami.default'
      username: stewart
      password: stJ0hnstuHARBOR #todo: replace with secret
      repo: 'harbor-bitnami.default/homelab/recruitunit'
      debug: true
      launch_debug: true
      insecure: true
    volumes:
      - name: temp-mount
        path: /dist
    commands:
      - docker build -t recruitunit:latest .
      - docker ps -a

volumes:
  - name: temp-mount
    temp: {}